# Generated by Django 3.1.5 on 2021-01-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=128)),
            ],
        ),
    ]
